<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <OutputPath>E:\Documentos\Mods\FFXVI\Tools\Reloaded\Release\Mods\ff16.gameplay.truly_eikonic_spells</OutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ModConfig.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ModConfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="icon.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ff16.utility.modloader.Interfaces" Version="1.0.5" />
    <PackageReference Include="FF16Framework.Interfaces" Version="1.2.0" />
    <PackageReference Include="FF16Tools.Files" Version="1.4.1" />
    <PackageReference Include="Reloaded.Memory" Version="9.4.1" />
    <PackageReference Include="Reloaded.Memory.Sigscan" Version="3.1.8" />
    <PackageReference Include="Reloaded.Memory.SigScan.ReloadedII.Interfaces" Version="1.2.0" />
    <PackageReference Include="Reloaded.Mod.Interfaces" Version="2.4.0" ExcludeAssets="runtime" />
    <PackageReference Include="Reloaded.SharedLib.Hooks" Version="1.9.0" />
    <PackageReference Include="NenTools.ImGui.Interfaces" Version="1.0.2" />

  </ItemGroup>

</Project>
