using System.Collections.Generic;

namespace ff16.gameplay.truly_eikonic_spells.GameApis.Magic;

internal enum MagicPropertyType
{
    Int,
    Float,
    Vec3Float,
    Vec3Int,
    Bool
}

internal record MagicPropertyInfo(string Name, MagicPropertyType Type);

internal static class MagicProperties
{
    public static readonly Dictionary<int, MagicPropertyInfo> Definitions = new()
    {
        { 2, new("Global Property?", MagicPropertyType.Int) },
        { 3, new("Value", MagicPropertyType.Float) },
        { 4, new("Value", MagicPropertyType.Float) },
        { 5, new("Value", MagicPropertyType.Float) },
        { 6, new("Value", MagicPropertyType.Float) },
        { 7, new("Value", MagicPropertyType.Int) },
        { 8, new("Speed", MagicPropertyType.Float) },
        { 9, new("Value", MagicPropertyType.Float) },
        { 10, new("Chance", MagicPropertyType.Float) },
        { 11, new("Value", MagicPropertyType.Float) },
        { 12, new("Value", MagicPropertyType.Float) },
        { 13, new("NoTrackingTarget", MagicPropertyType.Bool) },
        { 14, new("Value", MagicPropertyType.Float) },
        { 16, new("BoolValue", MagicPropertyType.Bool) },
        { 17, new("Value", MagicPropertyType.Int) },
        { 18, new("BoolValue", MagicPropertyType.Bool) },
        { 19, new("BoolValue", MagicPropertyType.Bool) },
        { 22, new("Vertical Angle Degrees offset", MagicPropertyType.Int) },
        { 24, new("UnkType", MagicPropertyType.Int) },
        { 26, new("OperationGroupId", MagicPropertyType.Int) },
        { 27, new("VFXAudioId", MagicPropertyType.Int) },
        { 28, new("Value", MagicPropertyType.Int) },
        { 29, new("Value", MagicPropertyType.Int) },
        { 30, new("Disappear after duration?", MagicPropertyType.Bool) },
        { 31, new("VFXScale", MagicPropertyType.Float) },
        { 32, new("Value", MagicPropertyType.Float) },
        { 35, new("ProjectileDuration (s)", MagicPropertyType.Float) },
        { 36, new("ProjectileRandDurationMinMax", MagicPropertyType.Vec3Float) },
        { 37, new("OnNoImpactOperationGroupId", MagicPropertyType.Int) },
        { 38, new("BoolValue", MagicPropertyType.Bool) },
        { 39, new("OperationGroupId", MagicPropertyType.Int) },
        { 41, new("AttackParamId", MagicPropertyType.Int) },
        { 42, new("Hitbox/Attachment Size", MagicPropertyType.Float) },
        { 43, new("Rate (Speed)", MagicPropertyType.Float) },
        { 44, new("Target", MagicPropertyType.Float) },
        { 45, new("Type", MagicPropertyType.Int) },
        { 46, new("Value", MagicPropertyType.Float) },
        { 47, new("Value", MagicPropertyType.Float) },
        { 48, new("Value", MagicPropertyType.Float) },
        { 49, new("Value", MagicPropertyType.Float) },
        { 52, new("Value", MagicPropertyType.Vec3Float) },
        { 53, new("Value", MagicPropertyType.Vec3Float) },
        { 54, new("Value", MagicPropertyType.Vec3Float) },
        { 55, new("Value", MagicPropertyType.Vec3Float) },
        { 56, new("Value", MagicPropertyType.Vec3Float) },
        { 57, new("Value", MagicPropertyType.Vec3Float) },
        { 58, new("Value", MagicPropertyType.Vec3Float) },
        { 59, new("Value", MagicPropertyType.Vec3Float) },
        { 60, new("Value", MagicPropertyType.Vec3Float) },
        { 61, new("Value", MagicPropertyType.Vec3Float) },
        { 62, new("Value", MagicPropertyType.Vec3Float) },
        { 63, new("Value", MagicPropertyType.Vec3Float) },
        { 64, new("Value", MagicPropertyType.Vec3Float) },
        { 65, new("Value", MagicPropertyType.Int) },
        { 66, new("Value", MagicPropertyType.Float) },
        { 68, new("Value", MagicPropertyType.Int) },
        { 69, new("Value", MagicPropertyType.Int) },
        { 70, new("Value", MagicPropertyType.Float) },
        { 71, new("Value", MagicPropertyType.Float) },
        { 72, new("Value", MagicPropertyType.Vec3Float) },
        { 73, new("Location spawn type ID", MagicPropertyType.Int) },
        { 74, new("Value", MagicPropertyType.Float) },
        { 75, new("Value", MagicPropertyType.Int) },
        { 76, new("Value", MagicPropertyType.Int) },
        { 77, new("Value", MagicPropertyType.Int) },
        { 78, new("Value", MagicPropertyType.Int) },
        { 79, new("Value", MagicPropertyType.Int) },
        { 80, new("Value", MagicPropertyType.Int) },
        { 81, new("EidId", MagicPropertyType.Int) },
        { 89, new("VfxAudioId", MagicPropertyType.Int) },
        { 90, new("Use property 91?", MagicPropertyType.Bool) },
        { 91, new("Value (MotionLayerSetId?)", MagicPropertyType.Int) },
        { 93, new("Value", MagicPropertyType.Float) },
        { 95, new("OnTargetHitOperationGroupIdCallback", MagicPropertyType.Int) },
        { 96, new("OperationGroupId", MagicPropertyType.Int) },
        { 97, new("Value", MagicPropertyType.Int) },
        { 98, new("Value", MagicPropertyType.Int) },
        { 99, new("Value", MagicPropertyType.Int) },
        { 102, new("OperationGroupId", MagicPropertyType.Int) },
        { 105, new("VFXAudioId", MagicPropertyType.Int) },
        { 109, new("Value", MagicPropertyType.Int) },
        { 110, new("OperationGroupId", MagicPropertyType.Int) },
        { 114, new("BoolValue", MagicPropertyType.Bool) },
        { 117, new("Value", MagicPropertyType.Float) },
        { 129, new("Value", MagicPropertyType.Float) },
        { 134, new("Value", MagicPropertyType.Int) },
        { 136, new("Value", MagicPropertyType.Int) },
        { 147, new("MagicId", MagicPropertyType.Int) },
        { 148, new("MagicId", MagicPropertyType.Int) },
        { 149, new("MagicId", MagicPropertyType.Int) },
        { 150, new("Value", MagicPropertyType.Int) },
        { 187, new("Type of trayectory ID", MagicPropertyType.Int) },
        { 997, new("Value", MagicPropertyType.Float) },
        { 1025, new("Value", MagicPropertyType.Int) },
        { 1026, new("Value", MagicPropertyType.Int) },
        { 1123, new("BoolValue", MagicPropertyType.Bool) },
        { 1231, new("Value", MagicPropertyType.Int) },
        { 1232, new("Value", MagicPropertyType.Int) },
        { 1379, new("ProjectileDuration (Scaled)", MagicPropertyType.Float) },
        { 1432, new("Value", MagicPropertyType.Int) },
        { 1458, new("LayoutInstanceId", MagicPropertyType.Int) },
        { 1484, new("Value", MagicPropertyType.Float) },
        { 1490, new("Value", MagicPropertyType.Int) },
        { 1503, new("OperationGroupId", MagicPropertyType.Int) },
        { 1686, new("Value", MagicPropertyType.Float) },
        { 1688, new("Value", MagicPropertyType.Float) },
        { 1791, new("Value", MagicPropertyType.Int) },
        { 1793, new("Value", MagicPropertyType.Float) },
        { 1807, new("Value", MagicPropertyType.Vec3Float) },
        { 1833, new("OperationGroupId", MagicPropertyType.Int) },
        { 1957, new("BoolValue", MagicPropertyType.Bool) },
        { 1994, new("Value", MagicPropertyType.Int) },
        { 1997, new("Value", MagicPropertyType.Vec3Float) },
        { 1999, new("Angle", MagicPropertyType.Float) },
        { 2000, new("Angle", MagicPropertyType.Float) },
        { 2060, new("Value", MagicPropertyType.Float) },
        { 2061, new("Value", MagicPropertyType.Int) },
        { 2062, new("Value", MagicPropertyType.Int) },
        { 2063, new("Value", MagicPropertyType.Int) },
        { 2064, new("Value", MagicPropertyType.Int) },
        { 2065, new("Value", MagicPropertyType.Int) },
        { 2066, new("Value", MagicPropertyType.Int) },
        { 2067, new("Value", MagicPropertyType.Int) },
        { 2068, new("Value", MagicPropertyType.Int) },
        { 2069, new("Value", MagicPropertyType.Int) },
        { 2211, new("Value", MagicPropertyType.Float) },
        { 2227, new("BoolValue", MagicPropertyType.Bool) },
        { 2259, new("Value", MagicPropertyType.Int) },
        { 2260, new("Value", MagicPropertyType.Int) },
        { 2319, new("Value", MagicPropertyType.Int) },
        { 2351, new("Value", MagicPropertyType.Float) },
        { 2359, new("BoolValue", MagicPropertyType.Bool) },
        { 2396, new("LayoutInstanceId", MagicPropertyType.Int) },
        { 2413, new("Value", MagicPropertyType.Int) },
        { 2414, new("Value", MagicPropertyType.Int) },
        { 2430, new("Trajectory variables (Rotation)", MagicPropertyType.Vec3Float) },
        { 2528, new("Value", MagicPropertyType.Int) },
        { 2529, new("Value", MagicPropertyType.Int) },
        { 2593, new("Trayectory intensity curve strength", MagicPropertyType.Float) },
        { 2575, new("Value", MagicPropertyType.Int) },
        { 2604, new("Value", MagicPropertyType.Int) },
        { 2672, new("Value", MagicPropertyType.Int) },
        { 2798, new("Value", MagicPropertyType.Int) },
        { 2856, new("BoolValue", MagicPropertyType.Bool) },
        { 2857, new("Value", MagicPropertyType.Float) },
        { 2906, new("Value", MagicPropertyType.Int) },
        { 3078, new("Value", MagicPropertyType.Int) },
        { 3079, new("Value", MagicPropertyType.Int) },
        { 3171, new("Value", MagicPropertyType.Float) },
        { 3172, new("Value", MagicPropertyType.Float) },
        { 3362, new("Value", MagicPropertyType.Float) },
        { 3363, new("Value", MagicPropertyType.Int) },
        { 3434, new("Value", MagicPropertyType.Int) },
        { 3440, new("OperationGroupId", MagicPropertyType.Int) },
        { 3441, new("OperationGroupId", MagicPropertyType.Int) },
        { 3497, new("Value", MagicPropertyType.Vec3Float) },
        { 3498, new("Value", MagicPropertyType.Vec3Float) },
        { 3606, new("BoolValue", MagicPropertyType.Bool) },
        { 3608, new("OperationGroupId", MagicPropertyType.Int) },
        { 3609, new("OperationGroupId", MagicPropertyType.Int) },
        { 3658, new("Value", MagicPropertyType.Int) },
        { 3659, new("Value", MagicPropertyType.Int) },
        { 3691, new("OperationGroupId", MagicPropertyType.Int) },
        { 3692, new("OperationGroupId", MagicPropertyType.Int) },
        { 3693, new("OperationGroupId", MagicPropertyType.Int) },
        { 3721, new("BoolValue", MagicPropertyType.Bool) },
        { 3722, new("Value", MagicPropertyType.Int) },
        { 3785, new("Value", MagicPropertyType.Int) },
        { 3791, new("Value", MagicPropertyType.Int) },
        { 3802, new("Value", MagicPropertyType.Int) },
        { 3848, new("CameraFCurveId", MagicPropertyType.Int) },
        { 3850, new("CameraFCurveId", MagicPropertyType.Int) },
        { 3856, new("CameraFCurveId", MagicPropertyType.Int) },
        { 3938, new("LayoutInstanceId", MagicPropertyType.Int) },
        { 3961, new("Value", MagicPropertyType.Int) },
        { 3962, new("Value", MagicPropertyType.Int) },
        { 3681, new("Value", MagicPropertyType.Int) },
        { 3872, new("Value", MagicPropertyType.Int) },
        { 3906, new("Value", MagicPropertyType.Int) },
        { 3907, new("Value", MagicPropertyType.Float) },
        { 3970, new("Value", MagicPropertyType.Int) },
        { 4002, new("EidId", MagicPropertyType.Int) },
        { 4007, new("Value", MagicPropertyType.Float) },
        { 4008, new("Time", MagicPropertyType.Float) },
        { 4010, new("Value", MagicPropertyType.Float) },
        { 4011, new("Value", MagicPropertyType.Int) },
        { 4014, new("Value", MagicPropertyType.Vec3Float) },
        { 4101, new("Value", MagicPropertyType.Float) },
        { 4102, new("Value", MagicPropertyType.Float) },
        { 4107, new("Value", MagicPropertyType.Int) },
        { 4131, new("Value", MagicPropertyType.Int) },
        { 4132, new("Value", MagicPropertyType.Int) },
        { 4243, new("BoolValue", MagicPropertyType.Bool) },
        { 4278, new("Value", MagicPropertyType.Int) },
        { 4279, new("Value", MagicPropertyType.Int) },
        { 4327, new("Value", MagicPropertyType.Int) },
        { 4343, new("Value", MagicPropertyType.Int) },
        { 4387, new("BoolValue", MagicPropertyType.Bool) },
        { 4402, new("OperationGroupId", MagicPropertyType.Int) },
        { 4427, new("Value", MagicPropertyType.Int) },
        { 4436, new("Value", MagicPropertyType.Int) },
        { 4447, new("Value", MagicPropertyType.Int) },
        { 4509, new("Value", MagicPropertyType.Int) },
        { 4774, new("OperationGroupId", MagicPropertyType.Int) },
        { 4785, new("BoolValue", MagicPropertyType.Bool) },
        { 4829, new("Value", MagicPropertyType.Int) },
        { 4845, new("Value", MagicPropertyType.Int) },
        { 4846, new("Value", MagicPropertyType.Int) },
        { 4847, new("Rate", MagicPropertyType.Int) },
        { 4848, new("Target", MagicPropertyType.Int) },
        { 5101, new("Value", MagicPropertyType.Int) },
        { 5125, new("Value", MagicPropertyType.Int) },
        { 5274, new("CommandId", MagicPropertyType.Int) },
        { 5275, new("CommandId", MagicPropertyType.Int) },
        { 5276, new("SkillUpgradeLevel", MagicPropertyType.Int) },
        { 5312, new("Value", MagicPropertyType.Int) },
        { 5644, new("Value", MagicPropertyType.Vec3Float) },
        { 5671, new("Value", MagicPropertyType.Int) },
        { 5685, new("Value", MagicPropertyType.Int) },
        { 5838, new("Value", MagicPropertyType.Float) },
        { 5959, new("Color", MagicPropertyType.Vec3Float) },
        { 5989, new("Value", MagicPropertyType.Int) },
        { 6056, new("BoolValue", MagicPropertyType.Bool) },
        { 6107, new("OperationGroupId", MagicPropertyType.Int) },
        { 6179, new("Value", MagicPropertyType.Int) },
        { 6287, new("Value", MagicPropertyType.Float) },
        { 6299, new("Value", MagicPropertyType.Int) },
        { 6339, new("Value", MagicPropertyType.Int) },
        { 6340, new("Value", MagicPropertyType.Int) },
        { 6376, new("Value", MagicPropertyType.Int) },
        { 6383, new("BoolValue", MagicPropertyType.Bool) },
        { 6454, new("Value", MagicPropertyType.Int) },
        { 6459, new("Value", MagicPropertyType.Int) },
        { 6471, new("Value", MagicPropertyType.Int) },
        { 6474, new("OperationGroupId", MagicPropertyType.Int) },
        { 6475, new("OperationGroupId", MagicPropertyType.Int) },
        { 6515, new("OperationGroupId", MagicPropertyType.Int) },
        { 6516, new("OperationGroupId", MagicPropertyType.Int) },
        { 6596, new("BoolValue", MagicPropertyType.Bool) },
        { 6600, new("Value", MagicPropertyType.Float) },
        { 6775, new("Chance", MagicPropertyType.Float) },
        { 6776, new("BoolValue", MagicPropertyType.Bool) },
        { 6800, new("Value", MagicPropertyType.Int) },
        { 6801, new("Value", MagicPropertyType.Int) },
        { 6822, new("Value", MagicPropertyType.Int) },
        { 6825, new("BoolValue", MagicPropertyType.Bool) },
        { 6826, new("BoolValue", MagicPropertyType.Bool) },
        { 6831, new("Value", MagicPropertyType.Float) },
        { 6913, new("Value", MagicPropertyType.Int) },
        { 6975, new("Value", MagicPropertyType.Int) },
        { 6988, new("BoolValue", MagicPropertyType.Bool) },
        { 7028, new("Value", MagicPropertyType.Int) },
        { 7037, new("Value", MagicPropertyType.Float) },
        { 7121, new("Value", MagicPropertyType.Int) },
        { 7428, new("Value", MagicPropertyType.Int) },
        { 7429, new("Value", MagicPropertyType.Int) },
        { 7430, new("Value", MagicPropertyType.Int) },
        { 7585, new("Value", MagicPropertyType.Int) },
        { 7586, new("Value", MagicPropertyType.Int) },
        { 7587, new("Value", MagicPropertyType.Int) },
        { 7588, new("Value", MagicPropertyType.Int) },
        { 7791, new("Value", MagicPropertyType.Int) },
        { 7799, new("BoolValue", MagicPropertyType.Bool) },
        { 7807, new("Value", MagicPropertyType.Int) },
        { 7809, new("Value", MagicPropertyType.Int) },
        { 7811, new("BoolValue", MagicPropertyType.Bool) },
        { 7812, new("Value", MagicPropertyType.Int) },
        { 7813, new("BoolValue", MagicPropertyType.Bool) },
    };
}
